"""step2 hardening indexes and constraints

Revision ID: 102c692c1be2
Revises: 888176505d00
Create Date: 2026-08-13 09:23:56.703528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102c692c1be2'
down_revision: Union[str, Sequence[str], None] = '888176505d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_slots_facility_id'), table_name='appointment_slots')
    op.create_index('ix_appointment_slots_facility_id_start_time', 'appointment_slots', ['facility_id', 'start_time'], unique=False)
    op.drop_index(op.f('ix_appointments_shipment_id'), table_name='appointments')
    op.create_index('ix_appointments_shipment_id_status', 'appointments', ['shipment_id', 'status'], unique=False)
    op.drop_index(op.f('ix_eta_updates_shipment_id'), table_name='eta_updates')
    op.create_index('ix_eta_updates_shipment_id_update_timestamp', 'eta_updates', ['shipment_id', 'update_timestamp'], unique=False)
    op.create_index('ix_facility_checkins_facility_id', 'facility_checkins', ['facility_id'], unique=False)
    op.create_check_constraint(
        'ck_facility_rules_effective_end_after_start',
        'facility_rules',
        'effective_end IS NULL OR effective_end > effective_start',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_facility_rules_effective_end_after_start',
        'facility_rules',
        type_='check',
    )
    op.drop_index('ix_facility_checkins_facility_id', table_name='facility_checkins')
    op.drop_index('ix_eta_updates_shipment_id_update_timestamp', table_name='eta_updates')
    op.create_index(op.f('ix_eta_updates_shipment_id'), 'eta_updates', ['shipment_id'], unique=False)
    op.drop_index('ix_appointments_shipment_id_status', table_name='appointments')
    op.create_index(op.f('ix_appointments_shipment_id'), 'appointments', ['shipment_id'], unique=False)
    op.drop_index('ix_appointment_slots_facility_id_start_time', table_name='appointment_slots')
    op.create_index(op.f('ix_appointment_slots_facility_id'), 'appointment_slots', ['facility_id'], unique=False)
    # ### end Alembic commands ###
