"""create step 2 domain tables

Revision ID: 888176505d00
Revises: 
Create Date: 2026-08-13 09:12:46.123651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888176505d00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='entity_status', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_carriers_code')
    )
    op.create_table('facilities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='entity_status', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('appointment_slots',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FULL', 'CLOSED', name='appointment_slot_status', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity >= 0', name='ck_appointment_slots_capacity_non_negative'),
    sa.CheckConstraint('end_time > start_time', name='ck_appointment_slots_end_after_start'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointment_slots_facility_id', 'appointment_slots', ['facility_id'], unique=False)
    op.create_table('contacts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('contact_type', sa.Enum('FACILITY', 'CARRIER', 'CUSTOMER', 'DRIVER', 'OTHER', name='contact_type', native_enum=False), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=True),
    sa.Column('carrier_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='entity_status', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_carrier_id', 'contacts', ['carrier_id'], unique=False)
    op.create_index('ix_contacts_facility_id', 'contacts', ['facility_id'], unique=False)
    op.create_table('docks',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('dock_type', sa.String(length=64), nullable=False),
    sa.Column('max_weight_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_length_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temperature_controlled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'INACTIVE', name='dock_status', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_docks_facility_id', 'docks', ['facility_id'], unique=False)
    op.create_table('drivers',
    sa.Column('carrier_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='entity_status', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drivers_carrier_id', 'drivers', ['carrier_id'], unique=False)
    op.create_table('facility_rules',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.String(length=128), nullable=False),
    sa.Column('rule_value', sa.JSON(), nullable=False),
    sa.Column('effective_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facility_rules_facility_id', 'facility_rules', ['facility_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('carrier_id', sa.Uuid(), nullable=False),
    sa.Column('license_plate', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=64), nullable=False),
    sa.Column('max_weight_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_volume_cbm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('equipment_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='entity_status', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicles_carrier_id', 'vehicles', ['carrier_id'], unique=False)
    op.create_table('shipments',
    sa.Column('carrier_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('shipment_number', sa.String(length=64), nullable=False),
    sa.Column('origin_location', sa.Text(), nullable=False),
    sa.Column('destination_location', sa.Text(), nullable=False),
    sa.Column('origin_facility_id', sa.Uuid(), nullable=True),
    sa.Column('destination_facility_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'AT_FACILITY', 'DELIVERED', 'CANCELLED', name='shipment_status', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume_cbm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pallet_count', sa.Integer(), nullable=True),
    sa.Column('equipment_required', sa.String(length=64), nullable=True),
    sa.Column('scheduled_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_facility_id'], ['facilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_facility_id'], ['facilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_number')
    )
    op.create_index('ix_shipments_carrier_id', 'shipments', ['carrier_id'], unique=False)
    op.create_index('ix_shipments_destination_facility_id', 'shipments', ['destination_facility_id'], unique=False)
    op.create_index('ix_shipments_driver_id', 'shipments', ['driver_id'], unique=False)
    op.create_table('appointments',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_slot_id', sa.Uuid(), nullable=True),
    sa.Column('dock_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'HELD', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'EXPIRED', name='appointment_status', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_slot_id'], ['appointment_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_facility_id', 'appointments', ['facility_id'], unique=False)
    op.create_index('ix_appointments_shipment_id', 'appointments', ['shipment_id'], unique=False)
    op.create_table('driver_exceptions',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('exception_type', sa.Enum('TRAFFIC', 'BREAKDOWN', 'REPAIR', 'DELAY', 'OTHER', name='exception_type', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='exception_status', native_enum=False), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_driver_exceptions_shipment_id', 'driver_exceptions', ['shipment_id'], unique=False)
    op.create_table('eta_updates',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('previous_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('DRIVER', 'CARRIER', 'DISPATCH', 'SYSTEM', 'FACILITY', name='eta_source', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eta_updates_shipment_id', 'eta_updates', ['shipment_id'], unique=False)
    op.create_table('facility_checkins',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('dock_id', sa.Uuid(), nullable=True),
    sa.Column('checkin_type', sa.Enum('GATE_IN', 'YARD_ARRIVAL', 'DOCK_ARRIVAL', 'UNLOADING_COMPLETE', name='checkin_type', native_enum=False), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facility_checkins_shipment_id', 'facility_checkins', ['shipment_id'], unique=False)
    op.create_table('operational_messages',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'PHONE', name='message_channel', native_enum=False), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'DELIVERED', name='operational_message_status', native_enum=False), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operational_messages_contact_id', 'operational_messages', ['contact_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('shipment_id', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('driver_exception_id', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='chat_thread_status', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_exception_id'], ['driver_exceptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_threads_shipment_id', 'chat_threads', ['shipment_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('chat_thread_id', sa.Uuid(), nullable=False),
    sa.Column('sender_type', sa.Enum('DRIVER', 'DISPATCHER', 'FACILITY', 'SYSTEM', 'CARRIER', name='sender_type', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='message_direction', native_enum=False), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_chat_thread_id', 'chat_messages', ['chat_thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_chat_thread_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_chat_threads_shipment_id', table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index('ix_operational_messages_contact_id', table_name='operational_messages')
    op.drop_table('operational_messages')
    op.drop_index('ix_facility_checkins_shipment_id', table_name='facility_checkins')
    op.drop_table('facility_checkins')
    op.drop_index('ix_eta_updates_shipment_id', table_name='eta_updates')
    op.drop_table('eta_updates')
    op.drop_index('ix_driver_exceptions_shipment_id', table_name='driver_exceptions')
    op.drop_table('driver_exceptions')
    op.drop_index('ix_appointments_shipment_id', table_name='appointments')
    op.drop_index('ix_appointments_facility_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_shipments_driver_id', table_name='shipments')
    op.drop_index('ix_shipments_destination_facility_id', table_name='shipments')
    op.drop_index('ix_shipments_carrier_id', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_vehicles_carrier_id', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_facility_rules_facility_id', table_name='facility_rules')
    op.drop_table('facility_rules')
    op.drop_index('ix_drivers_carrier_id', table_name='drivers')
    op.drop_table('drivers')
    op.drop_index('ix_docks_facility_id', table_name='docks')
    op.drop_table('docks')
    op.drop_index('ix_contacts_facility_id', table_name='contacts')
    op.drop_index('ix_contacts_carrier_id', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_appointment_slots_facility_id', table_name='appointment_slots')
    op.drop_table('appointment_slots')
    op.drop_table('facilities')
    op.drop_table('carriers')
    # ### end Alembic commands ###
